"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
$username@\
$hostname\
$directory\
$git_branch\
$git_status\
$dotnet\
$python\
\n$character"""

[aws]
symbol = "\ue7ad"
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'
style = "orange"

[azure]
symbol = "\ue754"
format = '\[[$symbol($subscription)]($style)\]'
style = "blue"

[buf]
format = '\[[$symbol($version)]($style)\]'
style = "blue"

[bun]
format = '\[[$symbol($version)]($style)\]'
style = "red"

[c]
symbol = "\ue771"
format = '\[[$symbol($version(-$name))]($style)\]'
style = "blue"

[cmake]
symbol = "\ue794"
format = '\[[$symbol($version)]($style)\]'
style = "blue"

[cmd_duration]
format = '\[[took $duration]($style)\]'
style = "gray"

[container]
format = '\[[$symbol \[$name\]]($style)\]'
style = "cyan"

[cpp]
format = '\[[$symbol($version(-$name))]($style)\]'
style = "blue"

[direnv]
format = '\[[$symbol$loaded/$allowed]($style)\]'
style = "orange"

[docker_context]
symbol = "\ue7b0"
format = '\[[$symbol$context]($style)\]'
style = "cyan"

[dotnet]
symbol = "\ue77f"
format = '\[[$symbol ($version)($tfm)]($style)\]'
style = "purple"
detect_extensions = ['csproj', 'fsproj', 'xproj', 'sln', 'slnx']
detect_files = [
    'global.json',
    'project.json',
    'Directory.Build.props',
    'Directory.Build.targets',
    'Packages.props',
]
detect_folders = []
heuristic = true

[gcloud]
symbol = "\ue7f1"
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'
style = "blue"

[git_branch]
symbol = "\ue725"
format = '\[[$symbol $branch]($style)\]'
style = "purple"

[git_commit]
# symbol = "\ue729"
format = '\[[\($hash$tag\)]($style)\]'
style = "green"

[git_metrics]
format = '\[[+$added]($added_style)\]\[[-$deleted]($deleted_style)\]'
added_style = "green"
deleted_style = "red"

[git_state]
format = '\[[$state ($progress_current/$progress_total)]($style)\]'
style = "yellow"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'
style = "red"

[golang]
symbol = "\ue7ef"
format = '\[[$symbol($version)]($style)\]'
style = "cyan"

[gradle]
symbol = "\ue7f2"
format = '\[[$symbol($version)]($style)\]'
style = "cyan"

[helm]
symbol = "\ue7fb"
format = '\[[$symbol($version)]($style)\]'
style = "gray"

[hostname]
format = '\[[$ssh_symbol($hostname)]($style)\] '
ssh_only = false
style = "white"

[java]
symbol = "\ue738"
format = '\[[$symbol($version)]($style)\]'
style = "red"

[kubernetes]
symbol = "\ue81d"
format = '\[[$symbol$context( \($namespace\))]($style)\]'
style = "blue"

[localip]
format = '\[[$localipv4]($style)\]'
style = "yellow"

[lua]
symbol = "\ue826"
format = '\[[$symbol($version)]($style)\]'
style = "blue"

[maven]
symbol = "\ue82c"
format = '\[[$symbol($version)]($style)\]'
style = "red"

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\]'
style = "gray"

[nats]
format = '\[[$symbol$name]($style)\]'
style = "green"

[netns]
format = '\[[$symbol \[$name\]]($style)\]'
style = "gray"

[nodejs]
symbol = "\ue718"
format = '\[[$symbol($version)]($style)\]'
style = "green"

[os]
format = '\[[$symbol]($style)\]'
style = "blue"

[package]
format = '\[[$symbol$version]($style)\]'
style = "orange"

[python]
symbol = "\ue73c"
format = '\[[${symbol} ${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
style = "yellow"

[rlang]
symbol = "\ue881"
format = '\[[$symbol ($version)]($style)\]'
style = "blue"

[rust]
symbol = "\ue7a8"
format = '\[[$symbol($version)]($style)\]'
style = "orange"

[shell]
format = '\[[$indicator]($style)\]'
style = "gray"

[status]
format = '\[[$symbol$status]($style)\]'
style = "red"

[sudo]
format = '\[[as $symbol]($style)\]'
style = "blue"

[terraform]
symbol = "\ue8bd"
format = '\[[$symbol$workspace]($style)\]'
style = "purple"

[time]
format = ' [$time]($style)'
disabled = false
time_format = "%H:%M:%S"
style = "gray"
utc_time_offset = 'Europe/Berlin'

[username]
format = '[$user]($style)'
show_always = true
style_user = "blue"
style_root = "red"
aliases = { "DEME" = "me" }

[directory]
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Linux = "󰌽"
Alpine = ""
Arch = "󰣇"
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[>](bold fg:color_green)'
error_symbol = '[>](bold fg:color_red)'

[env_var.SHELL]
variable = 'SHELL'
default = 'unknown shell'

[env_var.USER]
default = 'unknown user'

# [custom.foo]
# command = 'echo foo'                       # shows output of command
# detect_files = ['foo']                     # can specify filters but wildcards are not supported
# when = ''' test "$HOME" = "$PWD" '''
# format = ' transcending [$output]($style)'

# [custom.time]
# command = 'time /T'
# detect_extensions = ['pst']                         # filters *.pst files
# shell = ['pwsh.exe', '-NoProfile', '-Command', '-']

# [custom.time-as-arg]
# command = 'time /T'
# detect_extensions = ['pst']                    # filters *.pst files
# shell = ['pwsh.exe', '-NoProfile', '-Command']
# use_stdin = false
