"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
$os\
$username@\
$hostname\
$aws\
$azure\
$gcloud\
$directory\
$git_branch\
$git_commit\
$git_status\
$c\
$cpp\
$java\
$golang\
$lua\
$nodejs\
$rlang\
$rust\
$dotnet\
$python\
$buf\
$bun\
$cmake\
$container\
$direnv\
$docker_context\
$gradle\
$helm\
$kubernetes\
$maven\
$terraform\
$time\
$nats\
$netns\
$shell\
$status\
$sudo\
$cmd_duration\
\n$character"""


palette = 'custom'

[palettes.custom]
color_red = "#cc241d"
color_green = "#33981a"
aws_color = "#FF9900"
azure_color = "#0078D4"
buf_color = "#4A44F2"
bun_color = "#FBF0DF"
c_color = "#A8B9CC"
cmake_color = "#064F8C"
cpp_color = "#00599C"
docker_color = "#2496ED"
dotnet_color = "#512BD4"
gcloud_color = "#4285F4"
git_color = "#F05032"
go_color = "#00ADD8"
gradle_color = "#02303A"
helm_color = "#0F1689"
java_color = "#007396"
kubernetes_color = "#326CE5"
lua_color = "#2C2D72"
maven_color = "#C71A36"
nodejs_color = "#339933"
python_color = "#3776AB"
# python_color = "#FFD43B"
rlang_color = "#276DC3"
rust_color = "#CE422B"
terraform_color = "#7B42BC"

[aws]
symbol = "\uF0E0F"
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'
style = 'aws_color'
[aws.profile_aliases]
very-long-profile-name = 'vlpn'
[aws.region_aliases]
eu-central-1 = 'EUW-FRA'
eu-central-2 = 'EUW-LHR'
us-east-1 = 'USE-IAD'
us-east-2 = 'USE-CLE'
us-west-1 = 'USW-SFO'
us-west-2 = 'USW-PDX'

[azure]
symbol = "\uF0805"
format = '\[[$symbol ($subscription)]($style)\]'
style = "azure_color"
disabled = false
[azure.subscription_aliases]
lz-online-isccb-d = "chatbot-DEV"
lz-online-isccb-q = "chatbot-QA"
lz-online-isccb-p = "chatbot-PROD"

[buf]
symbol = "\uF0FD8"
format = '\[[$symbol($version)]($style)\]'
style = 'buf_color'
detect_extensions = []
detect_files = ["buf.yaml", "buf.gen.yaml", "buf.work.yaml"]
detect_folders = []

[bun]
symbol = "\uE76F"
format = '\[[$symbol($version)]($style)\]'
style = 'bun_color'
detect_extensions = []
detect_files = ["bun.lock", "bun.lockb", "bunfig.toml"]
detect_folders = []

[c]
symbol = "\uF0671"
format = '\[[$symbol($version(-$name))]($style)\]'
style = 'c_color'
detect_extensions = []
detect_files = []
detect_folders = []
commands = [["cc", "--version"], ["gcc", "--version"], ["clang", "--version"]]

[character]
disabled = false
success_symbol = '[>](bold color_green)'
error_symbol = '[>](bold color_red)'

[claude_context]
[claude_model]
[claude_cost]

[cmake]
symbol = "\uE794"
format = '\[[$symbol($version)]($style)\]'
style = 'cmake_color'
detect_extensions = []
detect_files = ["CMakeLists.txt", "CMakeCache.txt"]
detect_folders = []

[cmd_duration]
format = '\[ran [$duration](bold)($style)\]'
style = 'gray'
show_milliseconds = true
show_notifications = true
min_time = 2_000
disabled = false

[container]
format = '\[[$symbol \[$name\]]($style)\]'
style = 'gray'

[cpp]
symbol = "\uF0672"
format = '\[[$symbol($version(-$name))]($style)\]'
style = 'cpp_color'
detect_extensions = [
    "cpp",
    "cc",
    "cxx",
    "c++",
    "hpp",
    "hh",
    "hxx",
    "h++",
    "tcc",
]
detect_files = []
detect_folders = []
commands = [
    [
        "c++",
        "--version",
    ],
    [
        "g++",
        "--version",
    ],
    [
        "clang++",
        "--version",
    ],
]

[directory]
style = "bold white"
format = '\[[$path]($style)\]'
truncation_length = 5
truncation_symbol = '../'
use_os_path_sep = true
home_symbol = '~'

[direnv]
format = '\[[$symbol$loaded/$allowed]($style)\]'
style = 'gray'
detect_extensions = []
detect_env_vars = ["DIRENV_FILE"]
detect_files = [".envrc"]
detect_folders = []

[docker_context]
symbol = "\uF0868"
format = '\[[$symbol$context]($style)\]'
style = 'docker_color'
detect_extensions = []
detect_files = [
    "compose.yml",
    "compose.yaml",
    "docker-compose.yml",
    "docker-compose.yaml",
    "Dockerfile",
]
detect_folders = []

[dotnet]
symbol = "\uF031B"
format = '\[[$symbol ($version)($tfm)]($style)\]'
style = 'dotnet_color'
detect_extensions = ['csproj', 'fsproj', 'xproj', 'sln', 'slnx']
detect_files = [
    'global.json',
    'project.json',
    'Directory.Build.props',
    'Directory.Build.targets',
    'Packages.props',
]
detect_folders = []
heuristic = true

[env_var.SHELL]
variable = 'SHELL'
default = 'unknown shell'

[env_var.USER]
default = 'unknown user'

[gcloud]
symbol = "\uE7F1"
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'
style = 'gcloud_color'
[gcloud.project_aliases]
very-long-project-name = 'avlpn'
[gcloud.region_aliases]
europe-west3-a = 'EUW-FRA'
europe-west3-b = 'EUW-FRA'
europe-west3-c = 'EUW-FRA'
us-west2-a = 'USW-LAX'
us-west2-b = 'USW-LAX'
us-west2-c = 'USW-LAX'
us-west1-a = 'USW-SFO'
us-west1-b = 'USW-SFO'
us-west1-c = 'USW-SFO'
northamerica-northeast1-a = 'NAM-YUL'
northamerica-northeast1-b = 'NAM-YUL'
northamerica-northeast1-c = 'NAM-YUL'
northamerica-northeast2-a = 'NAM-YYZ'
northamerica-northeast2-b = 'NAM-YYZ'
northamerica-northeast2-c = 'NAM-YYZ'

[git_branch]
# format = '\[[$symbol on $branch]($style)\]'
format = '\[[$symbol $branch]($style)'
style = 'bold git_color'
symbol = "\uE702"

[git_commit]
format = '[\(#$hash$tag\)]($style)\]'
style = "git_color"
only_detached = false
tag_disabled = false
tag_symbol = "\uF04f9"
disabled = false

[git_status]
format = '\[([$all_status$ahead_behind]($style))\]'
style = "bold git_color"
modified = "M"
untracked = "?"
staged = "+"
deleted = "D"
renamed = "R"
conflicted = "="

[golang]
symbol = "\uF07D3"
format = '\[[$symbol($version)]($style)\]'
style = "bold go_color"
detect_extensions = ["go"]
detect_files = [
    "go.mod",
    "go.sum",
    "go.work",
    "glide.yaml",
    "Gopkg.yml",
    "Gopkg.lock",
    ".go-version",
]
detect_folders = ["Godeps"]

[gradle]
symbol = "\uE7F2"
format = '\[[$symbol($version)]($style)\]'
style = "bold gradle_color"

[helm]
symbol = "\uE7FB"
format = '\[[$symbol($version)]($style)\]'
style = "bold helm_color"
detect_extensions = []
detect_files = ["helmfile.yaml", "Chart.yaml"]
detect_folders = []

[hostname]
format = '[$ssh_symbol($hostname)]($style)\]'
ssh_only = false
trim_at = "."
detect_env_vars = []
style = "bold white"
aliases = { "a" = "b" }

[java]
symbol = "\uF0B37"
format = '\[[$symbol($version)]($style)\]'
style = "bold java_color"

[kubernetes]
symbol = "\uF10FE"
format = '\[[$symbol$context( \($namespace\))]($style)\]'
style = "bold kubernetes_color"
context_aliases = {}
user_aliases = {}
detect_extensions = []
detect_files = []
detect_folders = []
detect_env_vars = []
contexts = []

[line_break]
disabled = false

[localip]
format = '\[[$localipv4]($style)\]'
style = "yellow"
disabled = false
ssh_only = false

[lua]
symbol = "\uF08B1"
format = '\[[$symbol($version)]($style)\]'
style = "bold lua_color"

[maven]
symbol = "\uE82C"
format = '\[[$symbol($version)]($style)\]'
style = "bold maven_color"

[mise]

[nats]
format = '\[[$symbol$name]($style)\]'
style = "bold gray"

[netns]
format = '\[[$symbol \[$name\]]($style)\]'
style = "bold gray"

[nodejs]
symbol = "\uF0399"
format = '\[[$symbol($version)]($style)\]'
style = "bold nodejs_color"
detect_extensions = ["js", "mjs", "cjs", "ts", "mts", "cts"]
detect_files = [
    "package.json",
    ".node-version",
    ".nvmrc",
    "!bunfig.toml",
    "!bun.lock",
    "!bun.lockb",
    "!deno.json",
    "!deno.jsonc",
    "!deno.lock",
]
detect_folders = ["node_modules"]

[os]
format = '\[[$symbol ]($style)'
style = "bold white"
disabled = false

[os.symbols]
Windows = "\uE8E5"
Ubuntu = "\U000F0548"
Raspbian = "\uE722"
Mint = "\U000F08ED"
Macos = "\U000F0035"
Linux = "\U000F033D"
Alpine = "\uE713"
Arch = "\U000F08C7"
Debian = "\U000F08DA"
Redhat = "\U000F111B"
RedHatEnterprise = "\U000F111B"

[python]
symbol = "\ue73c"
format = '\[[${symbol}${pyenv_prefix} (${version}) \(venv:$virtualenv\)]($style)\]'
style = "bold python_color"
detect_extensions = ['py', 'ipynb']
detect_files = [
    'requirements.txt',
    'pyproject.toml',
    'setup.py',
    'setup.cfg',
    '__init__.py',
]
detect_folders = []
generic_venv_names = ['.venv', 'venv']
python_binary = [
    [
        'uv',
        'run',
        '--no-python-downloads',
        'python',
    ],
    [
        '.venv/Scripts/python.exe',
    ],
    [
        'python',
    ],
    [
        'py',
    ],
]

[rlang]
symbol = "\uf07d4"
format = '\[[$symbol ($version)]($style)\]'
style = "bold rlang_color"
detect_extensions = ["R", "Rd", "Rmd", "Rproj", "Rsx"]
detect_files = ["DESCRIPTION"]
detect_folders = [".Rproj.user"]

[rust]
style = "bold rust_color"
detect_files = ["Cargo.toml"]
detect_extensions = ["rs"]
detect_folders = []

[shell]
format = '\[[$indicator]($style)\]'
style = "shell_color"
disabled = false

[status]
format = '\[[$symbol$status]($style)\]'
style = "red"

[sudo]
format = '\[[sudo cached]($style)\]'
style = "blue"
disabled = false

[terraform]
symbol = "\U000F1062"
format = '\[[$symbol$workspace]($style)\]'
style = "terraform_color"
detect_extensions = ["tf", "tfplan", "tfstate"]
detect_files = []
detect_folders = [".terraform"]
commands = [["terraform", "version"], ["tofu", "version"]]

[time]
format = '\[[$time]($style)\]'
disabled = false
time_format = "%H:%M:%S UTC%:::z"
style = "bold gray"
utc_time_offset = 'local'

[username]
format = '[$user]($style)'
show_always = true
style_user = 'bold blue'
style_root = 'bold red'
aliases = { "Administrator" = "Admin" }

[custom.dotnet-workspace]
command = "dotnet --version"
when = '[[ "$PWD" == *"/source/repos/"* ]]'
symbol = "\uE77F"
format = '\[[$symbol ($version)($tfm)]($style)\]'
style = "bold dotnet_color"

# [custom.foo]
# command = 'echo foo'                     # shows output of command
# detect_files = ['foo']                     # can specify filters but wildcards are not supported
# when = ''' test "$HOME" = "$PWD" '''
# symbol = "\uf1617"
# format = '\[[$symbol($version)]($style)\]'
# format = ' transcending [$output]($style)'

# [custom.time]
# command = 'time /T'
# detect_extensions = ['pst']                         # filters *.pst files
# shell = ['pwsh.exe', '-NoProfile', '-Command', '-']

# [custom.time-as-arg]
# command = 'time /T'
# detect_extensions = ['pst']                    # filters *.pst files
# shell = ['pwsh.exe', '-NoProfile', '-Command']
# use_stdin = false
