"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
$os\
$username@\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_status\
$dotnet\
$python\
$time\
\n$character"""

palette = 'custom'

[palettes.custom]
color_red = "#cc241d"
color_green = "#33981a"
aws_color = "#FF9900"
azure_color = "#0078D4"
buf_color = "#4A44F2"
bun_color = "#FBF0DF"
c_color = "#A8B9CC"
cmake_color = "#064F8C"
cpp_color = "#00599C"
docker_color = "#2496ED"
dotnet_color = "#512BD4"
gcloud_color = "#4285F4"
git_color = "#F05032"
go_color = "#00ADD8"
gradle_color = "#02303A"
helm_color = "#0F1689"
java_color = "#007396"
kubernetes_color = "#326CE5"
lua_color = "#2C2D72"
maven_color = "#C71A36"
nodejs_color = "#339933"
python_color = "#3776AB"
# python_color = "#FFD43B"
rlang_color = "#276DC3"
rust_color = "#CE422B"
terraform_color = "#7B42BC"

[aws]
symbol = "\uf0e0f"
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'
style = 'aws_color'
[aws.profile_aliases]
very-long-profile-name = 'vlpn'
[aws.region_aliases]
eu-central-1 = 'EUW-FRA'
eu-central-2 = 'EUW-LHR'
us-east-1 = 'USE-IAD'
us-east-2 = 'USE-CLE'
us-west-1 = 'USW-SFO'
us-west-2 = 'USW-PDX'

[azure]
symbol = "\uf0805"
format = '\[[$symbol ($subscription)]($style)\]'
style = "azure_color"
disabled = false
[azure.subscription_aliases]
very-long-subscription-name = 'vlsn'

[buf]
symbol = "\uf0fd8"
format = '\[[$symbol($version)]($style)\]'
style = 'buf_color'
detect_extensions = []
detect_files = []
detect_folders = []

[bun]
symbol = "\uE76F"
format = '\[[$symbol($version)]($style)\]'
style = 'bun_color'
detect_extensions = []
detect_files = []
detect_folders = []

[c]
symbol = "\uf0671"
format = '\[[$symbol($version(-$name))]($style)\]'
style = 'c_color'
detect_extensions = []
detect_files = []
detect_folders = []
commands = []

[cmake]
symbol = "\ue794"
format = '\[[$symbol($version)]($style)\]'
style = 'cmake_color'
detect_extensions = []
detect_files = []
detect_folders = []

[cpp]
symbol = "\uf0672"
format = '\[[$symbol($version(-$name))]($style)\]'
style = 'cpp_color'
detect_extensions = []
detect_files = []
detect_folders = []
commands = []

[cmd_duration]
format = '\[[took $duration]($style)\]'
style = 'gray'
show_milliseconds = true
show_notifications = true

[container]
format = '\[[$symbol \[$name\]]($style)\]'
style = 'gray'

[directory]
style = "#769ff0"
format = '\[[$path]($style)\]'
truncation_length = 5
truncation_symbol = '../'
use_os_path_sep = true
home_symbol = '~'

[direnv]
format = '\[[$symbol$loaded/$allowed]($style)\]'
style = 'gray'

[docker_context]
symbol = "\uf0868"
format = '\[[$symbol$context]($style)\]'
style = 'docker_color'
detect_extensions = []
detect_files = []
detect_folders = []

[dotnet]
symbol = "\uf031b"
format = '\[[$symbol ($version)($tfm)]($style)\]'
style = 'dotnet_color'
detect_extensions = ['csproj', 'fsproj', 'xproj', 'sln', 'slnx']
detect_files = [
    'global.json',
    'project.json',
    'Directory.Build.props',
    'Directory.Build.targets',
    'Packages.props',
]
detect_folders = []
heuristic = true

[gcloud]
symbol = "\uE7F1"
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'
style = 'gcloud_color'
[gcloud.project_aliases]
very-long-project-name = 'avlpn'
[gcloud.region_aliases]
europe-west3-a = 'EUW-FRA'
europe-west3-b = 'EUW-FRA'
europe-west3-c = 'EUW-FRA'
us-west2-a = 'USW-LAX'
us-west2-b = 'USW-LAX'
us-west2-c = 'USW-LAX'
us-west1-a = 'USW-SFO'
us-west1-b = 'USW-SFO'
us-west1-c = 'USW-SFO'
northamerica-northeast1-a = 'NAM-YUL'
northamerica-northeast1-b = 'NAM-YUL'
northamerica-northeast1-c = 'NAM-YUL'
northamerica-northeast2-a = 'NAM-YYZ'
northamerica-northeast2-b = 'NAM-YYZ'
northamerica-northeast2-c = 'NAM-YYZ'

[git_branch]
# format = '\[[$symbol on $branch]($style)\]'
format = '\[[$symbol $branch]($style)'
style = 'git_color'
symbol = "\ue702"

[git_commit]
format = '[\(#$hash$tag\)]($style)\]'
style = "git_color"
only_detached = false
tag_disabled = false
tag_symbol = "\uf04f9"
disabled = false

[git_status]
format = '\[([$all_status$ahead_behind]($style))\]'
style = "git_color"
modified = 'M'
untracked = '?'
staged = '+'
deleted = 'D'
renamed = 'R'
conflicted = '='

[golang]
symbol = "\uf07d3"
format = '\[[$symbol($version)]($style)\]'
style = 'go_color'

[gradle]
symbol = "\uE7F2"
format = '\[[$symbol($version)]($style)\]'
style = 'gradle_color'

[helm]
symbol = "\uE7FB"
format = '\[[$symbol($version)]($style)\]'
style = 'helm_color'

[hostname]
format = '[$ssh_symbol($hostname) ]($style)'
ssh_only = false
style = 'gray'

[java]
symbol = "\uf0b37"
format = '\[[$symbol($version)]($style)\]'
style = 'java_color'

[kubernetes]
symbol = "\uf10fe"
format = '\[[$symbol$context( \($namespace\))]($style)\]'
style = 'kubernetes_color'

[localip]
format = '\[[$localipv4]($style)\]'
style = "yellow"

[lua]
symbol = "\uf08b1"
format = '\[[$symbol($version)]($style)\]'
style = 'lua_color'

[maven]
symbol = "\uE82C"
format = '\[[$symbol($version)]($style)\]'
style = 'maven_color'

[nats]
format = '\[[$symbol$name]($style)\]'
style = 'gray'

[netns]
format = '\[[$symbol \[$name\]]($style)\]'
style = 'gray'

[nodejs]
symbol = "\uf0399"
format = '\[[$symbol($version)]($style)\]'
style = 'nodejs_color'
#symbol = "\U000F0626" json

[os]
format = '[$symbol ]($style)'
style = 'gray'
disabled = false

[os.symbols]
Windows = "\ue8e5"
Ubuntu = "\uf0548"
Raspbian = "\ue722"
Mint = "\uf08ed"
Macos = "\uf0035"
Linux = "\uf033d"
Alpine = "\ue713"
Arch = "\uf08c7"
Debian = "\uf08da"
Redhat = "\uf111b"
RedHatEnterprise = "\uf111B"

[package]
format = '\[[$symbol$version]($style)\]'
style = "orange"

[python]
symbol = "\uf0320"
format = '\[[${symbol} ${pyenv_prefix}(${version}) \(venv:$virtualenv\)]($style)\]'
style = 'python_color'
detect_extensions = ['py', 'ipynb']
detect_files = [
    'requirements.txt',
    'pyproject.toml',
    'setup.py',
    'setup.cfg',
    '__init__.py',
]
detect_folders = []
generic_venv_names = ['.venv', 'venv']


[rlang]
symbol = "\uf07d4"
format = '\[[$symbol ($version)]($style)\]'
style = 'rlang_color'

[rust]
symbol = "\uf1617"
format = '\[[$symbol($version)]($style)\]'
style = 'rust_color'

[shell]
format = '\[[$indicator]($style)\]'
style = 'shell_color'

[status]
format = '\[[$symbol$status]($style)\]'
style = "red"

[sudo]
format = '\[[as $symbol]($style)\]'
style = "blue"

[terraform]
symbol = "\U000F1062"
format = '\[[$symbol$workspace]($style)\]'
style = 'terraform_color'

[time]
format = '\[[$time]($style)\]'
disabled = false
time_format = "%H:%M:%S UTC%:::z"
style = "gray"
utc_time_offset = 'local'

[username]
format = '[$user]($style)'
show_always = true
style_user = 'white'
style_root = 'red'
aliases = { "MCDDESKTOP" = "MCDDESKTOP", "MCDLAPTOP" = "MCDLAPTOP" }

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[>](bold fg:color_green)'
error_symbol = '[>](bold fg:color_red)'

[env_var.SHELL]
variable = 'SHELL'
default = 'unknown shell'

[env_var.USER]
default = 'unknown user'

[custom.dotnet-workspace]
command = "dotnet --version"
when = '[[ "$PWD" == *"/source/repos/"* ]]'
symbol = "\uE77F"
format = '\[[$symbol ($version)($tfm)]($style)\]'
style = 'dotnet_color'

# [custom.foo]
# command = 'echo foo'                     # shows output of command
# detect_files = ['foo']                     # can specify filters but wildcards are not supported
# when = ''' test "$HOME" = "$PWD" '''
# format = ' transcending [$output]($style)'

# [custom.time]
# command = 'time /T'
# detect_extensions = ['pst']                         # filters *.pst files
# shell = ['pwsh.exe', '-NoProfile', '-Command', '-']

# [custom.time-as-arg]
# command = 'time /T'
# detect_extensions = ['pst']                    # filters *.pst files
# shell = ['pwsh.exe', '-NoProfile', '-Command']
# use_stdin = false
